In [24]:
A = np.array([[1,0.75],[-1,0.75]])
A

array([[ 1.  ,  0.75],
       [-1.  ,  0.75]])

In [33]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.5       , -0.5       ],
       [ 0.66666667,  0.66666667]])

In [34]:
np.dot(Ainv, np.array([1,0])) , np.dot(Ainv, np.array([1,2])), np.dot(Ainv, np.array([-1,2]))

(array([0.5       , 0.66666667]),
 array([-0.5,  2. ]),
 array([-1.5       ,  0.66666667]))

In [3]:
def func(): 
    return 100 

In [4]:
func()

100

In [7]:
#indentation 
print("data1", end='\t')
print("data2", end="\n")
print("data3", end='\t')      

data1	data2
data3	

In [10]:
s1 = "data1"
s2 = "data2" 
print("this is a {}, {}.".format(s1,s2))

this is a data1, data2.


In [11]:
s1 = "andy"
s2 = "seoul"
print("this is a {name}, {addr}.".format(addr=s2, name=s1))

this is a andy, seoul.


In [12]:
a, b = 1, "python"

In [13]:
a,b

(1, 'python')

In [14]:
#Number - complex 
a = 2 + 3j 
b = complex(2,-2)
a,b

((2+3j), (2-2j))

In [16]:
a.real , a.imag

(2.0, 3.0)

In [19]:
a, a.conjugate()

((2+3j), (2-3j))

In [20]:
abs(a)

3.605551275463989

In [23]:
a = """
data science cheers
"""
print(a)


data science cheers



In [25]:
len(a)

21

In [30]:
a[1:3], a[:10], a[3:len(a)], a[::-1]

('da', '\ndata scie', 'ta science cheers\n', '\nsreehc ecneics atad\n')

In [33]:
a.upper().lower()

'\ndata science cheers\n'

In [34]:
#find 없는 문자열을 넣으면 -1을 리턴 
a.find('c')

7

In [35]:
a.find('z')

-1

In [37]:
#index
a.index('i')

8

In [40]:
#패턴
b = "asdfqweras"
c = 'qw'
b.count("as")

2

In [39]:
b.count(c)

1

In [41]:
#strip 
s = " data science "

In [49]:
s, s.lstrip(), s.rstrip() , 

(' data science ', 'data science ', ' data science')

In [50]:
s.strip()

'data science'

In [51]:
#replace 
s.replace("data", "computer")

' computer science '

In [52]:
s

' data science '

In [54]:
s.split(" ")

['', 'data', 'science', '']

In [56]:
s = "data,scinece,digital,marketing"
s.split(",")

['data', 'scinece', 'digital', 'marketing']

In [59]:
#list offset
ls = ["fast", "campus", "data", "science"]
ls[2]

'data'

In [60]:
ls[::-1]

['science', 'data', 'campus', 'fast']

In [63]:
ls[0] = "faster"
ls

['faster', 'campus', 'data', 'science']

In [65]:
ls.append("Jacob")
ls

['faster', 'campus', 'data', 'science', 'Jacob', 'Jacob']

In [68]:
ls = list(set(ls))

In [69]:
ls

['data', 'faster', 'science', 'Jacob', 'campus']

In [71]:
ls.sort()
ls

['Jacob', 'campus', 'data', 'faster', 'science']

In [72]:
ls.reverse()
ls

['science', 'faster', 'data', 'campus', 'Jacob']

In [73]:
ls.index("data")

2

In [75]:
ls.insert(0, "data")
ls

['data', 'data', 'science', 'faster', 'data', 'campus', 'Jacob']

In [76]:
ls.remove("data")

In [77]:
ls

['data', 'science', 'faster', 'data', 'campus', 'Jacob']

In [78]:
ls.pop()

'Jacob'

In [79]:
ls = ['science', 'dss8', 'data']
ls

['science', 'dss8', 'data']

In [81]:
ls[1:3] = "fast"

In [82]:
ls

['science', 'f', 'a', 's', 't']

In [83]:
ls[1] ="fast"

In [84]:
ls

['science', 'fast', 'a', 's', 't']

In [86]:
#list copy 
a = [1,2,3]
b = a 
a,b

([1, 2, 3], [1, 2, 3])

In [87]:
b[2] = 10 

In [88]:
a, b

([1, 2, 10], [1, 2, 10])

In [90]:
c = a.copy()
c

[1, 2, 10]

In [92]:
c[0] = 7
a,b,c

([1, 2, 10], [1, 2, 10], [7, 2, 10])

In [93]:
dic = {
    1:"one",
    "A":["data", "science"],
    "숫자":1234,
}

In [94]:
dic.items()

dict_items([(1, 'one'), ('A', ['data', 'science']), ('숫자', 1234)])

In [103]:
ls1 = [1,2,3,4]
ls2 = [5,6,7,8]
for a, b in zip(ls1,ls2) :
    print(a,b)

1 5
2 6
3 7
4 8


##### Set 
- 중복되는 데이터가 없는 집합 형태의 데이터 타입입니다.
- 합집합, 차집합, 교집합과 같은 집합의 연산이 가능 
- 순서 x 
- 리스트 데이터에서 중복을 제거할떄 사용가ㅡㄴㅇ

##### 데이터 형변환
- 변수의 데이터 타입을 변경하는 것입니다.
- 데이터의 값과 변경하려는 데이터의 타입에 따라서 변경이 불가능 할 수 도 있습니다.

In [104]:
a = "1"
type(int(a))

int

In [111]:
a = 1 
s = str(a)
type(s)

str

In [113]:
a = "1234"
s = int(a)
type(s)

int

In [115]:
s + 1

1235

In [117]:
#Boolean 데이터 타입으로의 형 변환 
bool(""), bool("a")

(False, True)

In [120]:
bool(-1),bool(1324), bool(0)

(True, True, False)

In [123]:
bool([]), bool([1,2,3])

(False, True)

In [126]:
s = "list"
list(s)

['l', 'i', 's', 't']

In [129]:
#튜플과 딕셔너리의 데이터 형변환 
#튜플 -> 딕셔너리 : 튜플데이터가 (key, value) 형태로 선언이 되어야 합니다.
t =((1,"one"), (2,"two"))
a = dict(t)
a

{1: 'one', 2: 'two'}

In [130]:
a.items()

dict_items([(1, 'one'), (2, 'two')])

##### Input, output, condition, loop

In [133]:
s = input("insert string:")

insert string:1234


In [135]:
s, type(s)

('1234', str)

In [136]:
s = int(input("insert string:"))

insert string:1234


In [138]:
s, type(s)

(1234, int)

In [145]:
ls = input("insert list (sep=',') : ")

insert list (sep=',') : a,b,c,abcd


In [146]:
ls

'a,b,c,abcd'

In [147]:
ls.split(',')

['a', 'b', 'c', 'abcd']

In [150]:
flag = False
if flag: 
    print("Eye")
print("Yo")

Yo


In [151]:
star1 = 4
star2 = 2 

if star1 > 3 :
    print("good")
else : 
    print("what?")

good


In [152]:
point = 74

if point > 90:
    print("A")
elif point > 80:
    print("B")
elif point > 70:
    print("C")
elif point > 60:
    print("D")
else:
    print("F")

C


In [153]:
# 숫자를 입력받아서 짝수이면 even, 홀수 odd 출력하는 프로그램을 작성하세요.
number = int(input("please insert number : "))
if number % 2 == 0 :
    print("even")
else :
    print("odd")

please insert number : 4
even


In [ ]:
#삼항 연산
#result = (True) if <condition> else (False)

In [156]:
number = 12423423 
result = "Even" if number % 2 == 0 else "Odd" 
print(result)

Odd


##### 반복문 
- while, for, break, continue, list comprehension 

```
while <조건> : 
    cod 
```

In [157]:
a = 3 
while a > 0 : 
    print(a)
    a -= 1
print(a)

3
2
1
0


In [160]:
# break
a = 0
while True:
    print(a) 
    if a == 3 :
        break
    a += 1 
a

0
1
2
3


3

In [163]:
# continue 
a = 5 
while a > 0 : 
    a -= 1 
    if a % 2 != 0 : 
        continue 
    print("even", a )

even 4
even 2
even 0


##### for 
```
for <var> in <list>:
    <code>
```

In [164]:
ls = [1,2,3]
for value in ls : 
    if value == 2 :
        break 
    print(value)

1


In [165]:
ls = [1,2,3]
for value in ls : 
    if value % 2 == 0 :
        continue
    print(value)

1
3


In [166]:
list(range(0,5,2))

[0, 2, 4]

In [167]:
for idx in range(5):
    print(idx)

0
1
2
3
4


In [168]:
for _ in range(5):
    print("dss")

dss
dss
dss
dss
dss


In [ ]:
#zip  : 2개의 리스트를 key value 형태로 묶어주는 함수 

In [169]:
subs = ["math","korean","science"]
points = [100,80,90]
dic = {} 

for idx in range(len(subs)):
    print(subs[idx], points[idx])
    dic[subs[idx]] = points[idx]
dic

math 100
korean 80
science 90


{'math': 100, 'korean': 80, 'science': 90}

In [170]:
for sub, point in zip(subs, points):
    dic[sub] = point 
dic

{'math': 100, 'korean': 80, 'science': 90}

In [175]:
subs, points
dict(zip(subs,points))

{'math': 100, 'korean': 80, 'science': 90}

In [177]:
#enumerate : 리스트 데이터를 index와 value 동시에 사용하고 싶을떄 
ls = ["data","dss","science", "dss"]
for idx, value in enumerate(ls):
    print(idx,value)

0 data
1 dss
2 science
3 dss


In [180]:
ls = ["data","dss","science", "dss"]

dss_idx = []
for idx, value in enumerate(ls) : 
    if value == "dss":
        dss_idx.append(idx)
print(dss_idx)

[1, 3]


In [181]:
# for 문을 이용해서 리스트안에 있는 모든 숫자를 더하는 코딩을 하세요.
ls = [1,3,5,7,9]
result = 0

# TODO
for num in ls :
    result += num
    
result

25

In [183]:
sum(ls)

25

##### List comprehension 

- 반복문의 리스트 결과를 한줄로 코딩하여 바로 만들어주는 방법 
- 리스트 데이터를 만들때, for 문보다 속도가 빠릅니다.( 만들수 있는 for문이 있고 만들수 없는 for문이 있다.)

In [188]:
ls = [] 
ls = [1,2,3,4,5]
print(ls)

#append 이용해서 추가 가능 

#for 문 
ls = [] 
for num in range(1,6):
    ls.append(num)
ls

ls = [num for num in range(1,6)]
ls

[1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]

In [193]:
# 0 - 10 까지 숫자를 출력하고 , 
#출력되는 숫자 뒤에 홀수 인지 짝수인지 문자열 붙여서 출력하는 코드 
ls  = [ str(num) + ":Even" if num % 2 == 0 else str(num) + ":Odd" for num in range(0,10)]
ls

['0:Even',
 '1:Odd',
 '2:Even',
 '3:Odd',
 '4:Even',
 '5:Odd',
 '6:Even',
 '7:Odd',
 '8:Even',
 '9:Odd']

In [194]:
[ num for num in range(11) if num % 2 != 0 ]

[1, 3, 5, 7, 9]

In [210]:
# 퀴즈 - lee 성을 가진 사람을 없애는 것 - 해보기 
names = ["kim dss", "park python", "lee data", "lee school", "jung science"]


ls = [name.split(" ")[1] if name.split(" ")[0] == 'lee' else name for name in names]
ls
 

['kim dss', 'park python', 'data', 'school', 'jung science']

In [213]:
names = ["kim dss", "park python", "lee data", "lee school", "jung science"]
[name for name in names if name.split(" ")[0] != 'lee' ]

['kim dss', 'park python', 'jung science']