In [24]:
A = np.array([[1,0.75],[-1,0.75]])
A

array([[ 1.  ,  0.75],
       [-1.  ,  0.75]])

In [33]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.5       , -0.5       ],
       [ 0.66666667,  0.66666667]])

In [34]:
np.dot(Ainv, np.array([1,0])) , np.dot(Ainv, np.array([1,2])), np.dot(Ainv, np.array([-1,2]))

(array([0.5       , 0.66666667]),
 array([-0.5,  2. ]),
 array([-1.5       ,  0.66666667]))